<a href="https://colab.research.google.com/github/DarshanSuresh/Data-Mining/blob/main/LAB_08_19_March_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 08 - 19 March 2024

In [ ]:
import pandas as pd

df = pd.read_csv('iris.csv')
df.head(5)


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           NaN          0.2  setosa
2           NaN          3.2           1.3          0.2  setosa
3           4.6          NaN           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.tail(5)

sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [ ]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    149.000000   149.000000    149.000000   150.000000
mean       5.851007     3.053691      3.774497     1.198667
std        0.825491     0.435040      1.759651     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.400000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  149 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  149 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
# calculate the mean of Sepal Length
sepallength_mean= df['sepal_length'].mean()
print('The mean of Sepal Length', sepallength_mean)

The mean of Sepal Length 5.851006711409395


In [ ]:
# calculate the mean of Sepal Width
sepalwidth_mean= df['sepal_width'].mean()
print('The mean of Sepal Width', sepalwidth_mean)

The mean of Sepal Width 3.053691275167785


In [ ]:
# calculate the mean of Petal Length
petallength_mean= df['petal_length'].mean()
print('The mean of Petal Length', petallength_mean)

The mean of Petal Length 3.774496644295302


In [ ]:
# calculate the mean of Petal Width
petalwidth_mean= df['petal_width'].mean()
print('The mean of Petal Width', petalwidth_mean)

The mean of Petal Width 1.1986666666666668


## Replacing NAN with the use of mean

In [ ]:
import numpy as np
df['sepal_length'].replace(np.nan,sepallength_mean,inplace=True)

In [ ]:
df.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0      5.100000          3.5           1.4          0.2  setosa
1      4.900000          3.0           NaN          0.2  setosa
2      5.851007          3.2           1.3          0.2  setosa
3      4.600000          NaN           1.5          0.2  setosa
4      5.000000          3.6           1.4          0.2  setosa

In [ ]:
df['sepal_width'].replace(np.nan,sepalwidth_mean,inplace=True)

In [ ]:
df.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0      5.100000     3.500000           1.4          0.2  setosa
1      4.900000     3.000000           NaN          0.2  setosa
2      5.851007     3.200000           1.3          0.2  setosa
3      4.600000     3.053691           1.5          0.2  setosa
4      5.000000     3.600000           1.4          0.2  setosa

In [ ]:
df['petal_length'].replace(np.nan,petallength_mean,inplace=True)

In [ ]:
df.head(5)

sepal_length  sepal_width  petal_length  petal_width species
0      5.100000     3.500000      1.400000          0.2  setosa
1      4.900000     3.000000      3.774497          0.2  setosa
2      5.851007     3.200000      1.300000          0.2  setosa
3      4.600000     3.053691      1.500000          0.2  setosa
4      5.000000     3.600000      1.400000          0.2  setosa

In [ ]:
X=df.iloc[:,0]
X

0      5.100000
1      4.900000
2      5.851007
3      4.600000
4      5.000000
         ...   
145    6.700000
146    6.300000
147    6.500000
148    6.200000
149    5.900000
Name: sepal_length, Length: 150, dtype: float64

In [ ]:
Y=df.iloc[:,1]
Y

0      3.500000
1      3.000000
2      3.200000
3      3.053691
4      3.600000
         ...   
145    3.000000
146    2.500000
147    3.000000
148    3.400000
149    3.000000
Name: sepal_width, Length: 150, dtype: float64

## Training & Testing for Iris DataSet

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.2)

In [ ]:
print('X Train:')
x_train = np.array(x_train).reshape(-1,1)
print(x_train)

X Train:
[[5.7       ]
 [6.3       ]
 [4.4       ]
 [5.6       ]
 [4.9       ]
 [4.6       ]
 [6.7       ]
 [4.8       ]
 [5.2       ]
 [4.3       ]
 [5.        ]
 [5.4       ]
 [6.5       ]
 [5.7       ]
 [5.9       ]
 [7.2       ]
 [4.8       ]
 [5.7       ]
 [6.1       ]
 [6.5       ]
 [6.2       ]
 [5.8       ]
 [5.5       ]
 [6.4       ]
 [4.8       ]
 [4.7       ]
 [5.        ]
 [4.4       ]
 [6.8       ]
 [4.9       ]
 [5.5       ]
 [4.6       ]
 [6.8       ]
 [6.7       ]
 [7.7       ]
 [5.5       ]
 [6.2       ]
 [6.5       ]
 [4.4       ]
 [5.        ]
 [6.3       ]
 [6.3       ]
 [5.4       ]
 [6.        ]
 [6.        ]
 [4.5       ]
 [5.4       ]
 [5.8       ]
 [4.9       ]
 [6.5       ]
 [6.7       ]
 [6.4       ]
 [6.3       ]
 [5.2       ]
 [6.4       ]
 [7.1       ]
 [6.7       ]
 [6.9       ]
 [6.9       ]
 [4.9       ]
 [5.8       ]
 [6.5       ]
 [5.9       ]
 [7.2       ]
 [6.7       ]
 [5.        ]
 [5.1       ]
 [6.9       ]
 [5.6       ]
 [5.1       ]
 [6.3      

In [ ]:
print('X Test:')
x_test = np.array(x_test).reshape(-1,1)
print(x_test)

X Test:
[[6.7]
 [4.8]
 [5.4]
 [5.9]
 [4.9]
 [5.2]
 [5. ]
 [4.6]
 [7.2]
 [5.1]
 [6. ]
 [5.7]
 [6.7]
 [5.8]
 [7.7]
 [6.6]
 [6. ]
 [6.2]
 [5. ]
 [6.6]
 [6.3]
 [5. ]
 [6.9]
 [6.1]
 [7.3]
 [4.6]
 [6.1]
 [5.1]
 [6.3]
 [5.5]]


In [ ]:
print('Y Train:')
y_train = np.array(y_train).reshape(-1,1)
print(y_train)

Y Train:
[[2.9]
 [2.3]
 [3.2]
 [3. ]
 [2.5]
 [3.6]
 [2.5]
 [3.4]
 [2.7]
 [3. ]
 [2. ]
 [3.4]
 [2.8]
 [2.5]
 [3.2]
 [3.6]
 [3. ]
 [2.6]
 [2.6]
 [3. ]
 [2.9]
 [2.7]
 [3.5]
 [3.2]
 [3.1]
 [3.2]
 [2.3]
 [3. ]
 [3.2]
 [2.4]
 [2.4]
 [3.4]
 [3. ]
 [3.3]
 [2.8]
 [2.4]
 [2.2]
 [3. ]
 [2.9]
 [3.3]
 [3.3]
 [3.3]
 [3. ]
 [2.9]
 [3.4]
 [2.3]
 [3.9]
 [2.8]
 [3. ]
 [3.2]
 [3. ]
 [2.8]
 [2.7]
 [4.1]
 [3.1]
 [3. ]
 [3.1]
 [3.1]
 [3.1]
 [3.1]
 [4. ]
 [3. ]
 [3. ]
 [3.2]
 [3.3]
 [3.5]
 [3.4]
 [3.2]
 [2.9]
 [3.7]
 [2.9]
 [3.1]
 [2.5]
 [2.8]
 [3.5]
 [2.9]
 [3.4]
 [3. ]
 [2.8]
 [3.4]
 [3.2]
 [2.6]
 [2.7]
 [2.6]
 [2.7]
 [2.3]
 [3.8]
 [3.5]
 [2.8]
 [3.1]
 [2.5]
 [3.4]
 [2.5]
 [3.8]
 [2.7]
 [2.5]
 [2.8]
 [2.7]
 [3. ]
 [3.5]
 [2.9]
 [3. ]
 [2.6]
 [3.2]
 [3.7]
 [2.7]
 [3.4]
 [2.8]
 [2.8]
 [3.8]
 [4.4]
 [3.7]
 [2.2]
 [3.4]
 [3. ]
 [2.8]
 [3.4]
 [3.2]
 [2.8]
 [3.4]]


In [ ]:
print('Y Test:')
y_test = np.array(y_test).reshape(-1,1)
print(y_test)

Y Test:
[[3.1       ]
 [3.        ]
 [3.9       ]
 [3.        ]
 [3.1       ]
 [3.5       ]
 [3.2       ]
 [3.05369128]
 [3.        ]
 [3.8       ]
 [3.        ]
 [3.8       ]
 [3.        ]
 [2.7       ]
 [3.8       ]
 [2.9       ]
 [2.2       ]
 [2.8       ]
 [3.6       ]
 [3.        ]
 [2.5       ]
 [3.        ]
 [3.1       ]
 [3.        ]
 [2.9       ]
 [3.2       ]
 [3.        ]
 [3.3       ]
 [2.8       ]
 [4.2       ]]


In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred_test=lr.predict(x_test)
y_pred_test

array([[2.99393265],
       [3.07404406],
       [3.04874572],
       [3.02766377],
       [3.06982767],
       [3.0571785 ],
       [3.06561128],
       [3.08247684],
       [2.9728507 ],
       [3.06139489],
       [3.02344738],
       [3.03609655],
       [2.99393265],
       [3.03188016],
       [2.95176875],
       [2.99814904],
       [3.02344738],
       [3.0150146 ],
       [3.06561128],
       [2.99814904],
       [3.01079821],
       [3.06561128],
       [2.98549987],
       [3.01923099],
       [2.96863431],
       [3.08247684],
       [3.01923099],
       [3.06139489],
       [3.01079821],
       [3.04452933]])

In [ ]:
var = np.array(4.5).reshape(-1,1)
var

array([[4.5]])

In [ ]:
y_pred_var = lr.predict(var)
y_pred_var

array([[3.08669323]])